name: Build google-benchmark
on: [push, pull_request, workflow_dispatch]

jobs:
  benchmarks-gcc:
    runs-on: ubuntu-latest
    container: gcc:12
    steps:
      - name: Install CMake
        run: apt update -qq && apt -y install cmake make git
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --target my_benchmarks --parallel
      - name: run
        run: |
          ./build/my_benchmarks

  benchmarks-clang:
    runs-on: ubuntu-latest
    container: silkeh/clang
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --target my_benchmarks --parallel
      - name: run
        run: |
          ./build/my_benchmarks

  benchmarks-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -G "Visual Studio 17 2022" -A x64
          cmake --build build/ --target my_benchmarks --config Release --parallel
      - name: run
        run: .\build\Release\my_benchmarks.exe