name: Build googletest
on: [push, pull_request, workflow_dispatch]

jobs:
  tests-gcc:
    runs-on: ubuntu-latest
    container: gcc:12
    steps:
      - name: Install CMake
        run: apt update -qq && apt -y install cmake make git
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --target my_tests --parallel
      - name: run
        run: |
          ./build/my_tests

  tests-gcc-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: apt update -qq && apt -y install g++-12 cmake make git
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="g++-12"
          cmake --build build/ --target my_tests --parallel
      - name: run
        run: |
          ./build/my_tests

  tests-clang:
    runs-on: ubuntu-latest
    container: silkeh/clang
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release
          cmake --build build/ --target my_tests --parallel
      - name: run
        run: |
          ./build/my_tests

  test-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cmake -B build/ -G "Visual Studio 17 2022" -A x64
          cmake --build build/ --target my_tests --config Release --parallel
      - name: run
        run: .\build\Release\my_tests.exe